#include QMK_KEYBOARD_H
#include "keymap_steno.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Qwerty
     * ,-----------------------------------------------------------------------------------.
     * | Tab  |   Q  |   W  |   E  |   R  |   T  |   Y  |   U  |   I  |   O  |   P  | Bksp |
     * |------+------+------+------+------+-------------+------+------+------+------+------|
     * | Esc/~|   A  |   S  |   D  |   F  |   G  |   H  |   J  |   K  |   L  |   ;  |  "   |
     * |------+------+------+------+------+------|------+------+------+------+------+------|
     * | Shift|   Z  |   X  |   C  |   V  |   B  |   N  |   M  |   ,  |   .  |   /  |Enter |
     * |------+------+------+------+------+------+------+------+------+------+------+------|
     * | Ctrl | GUI  | Alt  |PrScr |Lower |    Space    |Raise | Left | Down |  Up  |Right |
     * `-----------------------------------------------------------------------------------'
     */
    [0] = LAYOUT_ortho_4x12(
            KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,  KC_T,   KC_Y,   KC_U,  KC_I,    KC_O,    KC_P,    KC_BSPC,
            QK_GESC, KC_A,    KC_S,    KC_D,    KC_F,  KC_G,   KC_H,   KC_J,  KC_K,    KC_L,    KC_SCLN, KC_QUOT, 
            KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,  KC_B,   KC_N,   KC_M,  KC_COMM, KC_DOT,  KC_SLSH, KC_ENT, 
            KC_LCTL, KC_LGUI, KC_LALT, KC_PSCR, TO(2), KC_SPC, KC_SPC, TO(1), KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT
            ),
    /* Raise
     * ,-----------------------------------------------------------------------------------.
     * |   \  |   1  |   2  |   3  |   4  |   5  |   6  |   7  |   8  |   9  |   0  | Esc  |
     * |------+------+------+------+------+-------------+------+------+------+------+------|
     * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |  F7  |  F8  |  F9  | F10  | F11  | F12  |
     * |------+------+------+------+------+------|------+------+------+------+------+------|
     * |      |   -  |   +  | Ins  |  Del | Home | End  | PgDn | PgUp |   [  |   ]  |      |
     * |------+------+------+------+------+------+------+------+------+------+------+------|
     * |      |      |      |      |Lower |             |Raise |      |      |      |      |
     * `-----------------------------------------------------------------------------------'
     */

    [1] = LAYOUT_ortho_4x12(
            KC_BSLS, KC_1,    KC_2,    KC_3,    KC_4,   KC_5,   KC_6,     KC_7,    KC_8, KC_9, KC_0, KC_ESC, 
            KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,  KC_F6,   KC_F7,   KC_F8,   KC_F9, KC_F10, KC_F11, KC_F12, 
            KC_TRNS, KC_MINS, KC_EQL,  KC_INS,  KC_DEL, KC_HOME, KC_END,  KC_PGUP, KC_PGDN, KC_LBRC, KC_RBRC, KC_TRNS, 
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),  KC_TRNS, KC_TRNS, TO(3)  , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
            ),
    /* lower/plover layer (http://opensteno.rg)
     * ,-----------------------------------------------------------------------------------.
     * |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |
     * |------+------+------+------+------+-------------+------+------+------+------+------|
     * |  fn  |   s  |   t  |   p  |   h  |   *  |   *  |   f  |   p  |   l  |   t  |   d  |
     * |------+------+------+------+------+------|------+------+------+------+------+------|
     * |      |   s  |   k  |   w  |   r  |   *  |   *  |   r  |   b  |   g  |   s  |   z  |
     * |------+------+------+------+------+------+------+------+------+------+------+------|
     * |raise |      |      |   a  |   o  |             |   e  |   u  |  pwr | res1 | res2 |
     * `-----------------------------------------------------------------------------------'
     */

    [2] = LAYOUT_ortho_4x12(
            STN_N1,  STN_N2,  STN_N3,  STN_N4,  STN_N5,  STN_N6,  STN_N7,  STN_N8,  STN_N9,  STN_NA,  STN_NB,  STN_NC ,
            STN_FN,  STN_S1,  STN_TL,  STN_PL,  STN_HL,  STN_ST1, STN_ST3, STN_FR,  STN_PR,  STN_LR,  STN_TR,  STN_DR ,
            XXXXXXX, STN_S2,  STN_KL,  STN_WL,  STN_RL,  STN_ST2, STN_ST4, STN_RR,  STN_BR,  STN_GR,  STN_SR,  STN_ZR ,
            TO(0),  XXXXXXX, XXXXXXX, STN_A,    STN_O,   XXXXXXX, XXXXXXX, STN_E,   STN_U,   STN_PWR, STN_RE1, STN_RE2
            ),
  /* lower/plover layer (http://opensteno.rg)
     * ,-----------------------------------------------------------------------------------.
     * |  C   |  C#  |   D  |   D#  |  E  |   F  |  F#  |   G  |  G#  |   A  |  A#  |   B  |
     * |------+------+------+------+------+-------------+------+------+------+------+------|
     * |  C   |   D  |   E  |   F  |   G  |   A  |   B  |   C  |   D  |   E  |   F  |   G  |
     * |------+------+------+------+------+------|------+------+------+------+------+------|
     * |      |      |OctUp | VelUp|      |TrnsDn|TrnsUp|      | ChUp |BendUp|      |      |
     * |------+------+------+------+------+------+------+------+------+------+------+------|
     * |      |      |OctDn | VelDn| Extra|             |qwerty| ChDn |BendDn|      |      |
     * `-----------------------------------------------------------------------------------'
     */
    [3] = LAYOUT_ortho_4x12(
            MI_C_2,   MI_Cs_2, MI_D_2,  MI_Ds_2, MI_E_2,  MI_F_2,   MI_Fs_2,  MI_G_2,  MI_Gs_2, MI_A_2,   MI_As_2,  MI_B_2,
            MI_C_2,   MI_D_2,  MI_E_2,  MI_F_2,  MI_G_2,  MI_A_2,   MI_B_2,   MI_C_3,  MI_D_3,  MI_E_3,   MI_F_3,   MI_G_3,
            XXXXXXX,  XXXXXXX, MI_OCTU, MI_VELU, XXXXXXX, MI_TRNSD, MI_TRNSU, XXXXXXX, MI_CHU,  MI_BENDU, XXXXXXX,  XXXXXXX,
            XXXXXXX,  XXXXXXX, MI_OCTD, MI_VELD, TO(1),   XXXXXXX,  XXXXXXX,  TO(0),   MI_CHD,  MI_BENDD, XXXXXXX,  XXXXXXX
            )


};
void keyboard_post_init_user(void) {
  // Customise these values to desired behaviour
  debug_enable=true;
  debug_matrix=true;
  //debug_keyboard=true;
  //debug_mouse=true;
}
void eeconfig_init_user() {
    steno_set_mode(STENO_MODE_GEMINI); // or STENO_MODE_BOLT
}
